name: "Terraform Validate"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_OWNER: ${{ vars.GH_ORG }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_WORKSPACE: happypathway
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  
jobs:
  setup-terraform:
    outputs:
      commit_sha: ${{ steps.checkout.outputs.commit }}
        
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        id: checkout
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ vars.terraform_version }}
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
          cli_config_credentials_hostname: ${{ vars.terraform_api }}
          
      - name: terraform init
        run: terraform init -upgrade

      - uses: actions/upload-artifact@master
        name: Archive Configuration
        if: github.ref == 'refs/heads/main'
        with:
          name: terraform_dir
          path: examples/.terraform

      - uses: actions/upload-artifact@master
        name: Archive Lockfile
        if: github.ref == 'refs/heads/main'
        with:
          name: terraform_lockfile
          path: examples/.terraform.lock.hcl
     
  gtag:
    needs: terraform-validate
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    uses: HappyPathway/centralized-actions/.github/workflows/gtag.yml@main
    with:
      patch: true
      github_org: ${{ vars.GH_ORG }}
      github_username: ${{ vars.GH_USERNAME }}
      github_email: ${{ vars.GH_EMAIL }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
