name: "Terraform Validate"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_OWNER: ${{ vars.GH_ORG }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_WORKSPACE: happypathway
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  
jobs:
  gtag:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    uses: HappyPathway/centralized-actions/.github/workflows/gtag.yml@main
    with:
      patch: true
      github_org: ${{ vars.GH_ORG }}
      github_username: ${{ vars.GH_USERNAME }}
      github_email: ${{ vars.GH_EMAIL }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
